services:
  - type: web
    name: smart-expense-tracker
    runtime: java
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/expense-tracker-web-0.0.1-SNAPSHOT.jar"
    healthCheckPath: /login
    envVars:
      - key: SERVER_PORT
        value: 10000
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: expense-tracker-db 
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false

